version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:5.6.10
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
  
  memcached:
    image: memcached:1.5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - memcached
    volumes:
      - "./:/htools-api"
    env_file:
      - .env.default
      - .env

volumes:
  elasticsearch-data: {}